import Head from "next/head";
import Image from "next/image";
import { Heading, Text } from "@ignite-ui/react";
import { Hero, HomeContainer, Preview} from "./styles";

import previewImage from '../../assets/previewImage.png'
import { ClaimUserNameForm } from "./components/ClaimUserNameForm";

export default function Home(){
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer>
        <Hero>
          <Heading size={"4xl"}>
            Agendamento {'\n'} 
            descomplicado
          </Heading>
          <Text size={'xl'}>
            Conecte seu calendário e permita que as{'\n'}
            pessoas marquem agendamentos no seu tempo livre.
          </Text>
          <ClaimUserNameForm/>

        </Hero>
        <Preview>
          <Image 
            alt="calendário simulando a aplicação em desenvolvimento" 
            src={previewImage}
            quality={100}
            priority 
          />
        </Preview>
      </HomeContainer>
     
    </>

  )
}